### ISSUE TITLE
양희철님 코드리뷰

### ISSUE THREAD

**Issue by JaeSang1998** [heechul94/iron-todo-list#1]
안녕하세요 희철님 리뷰가 조금 늦었습니다 그래도 빡세게 봐야겠죠??

https://github.com/heechul94/iron-todo-list/blob/9778be11d9214a0e1e93cfe74a34a41699c34940/src/components/units/Todo/TodoListUI.jsx#L35-L44
불필요한 옵셔널 체이닝이 보이네요. 지금은 필요 없어보여서 지워주셔도 좋을 것 같습니다.
item.isDone === false === true 의 경우 item.isDone !item.isDone 등으로 좀 더 간결하게 표현할 수 있습니다.

TodoCard 에 있는 props 와 이름이 같을때에는
```
  <TodoCard
                            key={item.id}
                            cardId={item.id}
                            onClickButtonHandler={onClickButtonHandler}
                            {...item}
                        />
```

이렇게도 표현이 가능합니다.

https://github.com/heechul94/iron-todo-list/blob/9778be11d9214a0e1e93cfe74a34a41699c34940/src/components/units/Todo/TodoListUI.jsx#L46

앞의 값이 명확히 없을때에는 null 을 넣어주시는게 더 좋습니다. 불필요한 스타일링이나 블록을 방지하는거죠.

https://github.com/heechul94/iron-todo-list/blob/9778be11d9214a0e1e93cfe74a34a41699c34940/src/components/units/Todo/TodoListContainer.jsx#L16

onClickHandler 의 역할이 너무 많습니다. status 를 통해서 분리해주시는 것은 좋지만 둘중에 하나는 행해졌어야합니다.

1. Reducer 의 역할을 하기 위한것이었다면 아래에 있는 case 들이 각각 다른 함수로 분리되어 있었어야함
2. 애초에 다른 함수로 사용

https://github.com/heechul94/iron-todo-list/blob/9778be11d9214a0e1e93cfe74a34a41699c34940/src/components/units/Todo/TodoListContainer.jsx#L23

id 를 고유하게 쓰기위해서 많은 노력을 하셨군요!
uuid, Date.now(), crypto 객체등을 이용하면 좀 더 편리하게 작업하실 수 있을거에요!

https://github.com/heechul94/iron-todo-list/blob/9778be11d9214a0e1e93cfe74a34a41699c34940/src/components/units/Todo/TodoListContainer.jsx#L18-L19
https://github.com/heechul94/iron-todo-list/blob/9778be11d9214a0e1e93cfe74a34a41699c34940/src/components/units/Todo/TodoListContainer.jsx#L38

filter, map 메서드 자체가 새로운 배열을 반환하니 ... 연산자는 필요 없을 것 같네요.

https://github.com/heechul94/iron-todo-list/blob/9778be11d9214a0e1e93cfe74a34a41699c34940/src/components/commons/Buttons/NormalButton.jsx#L15-L22
https://github.com/heechul94/iron-todo-list/blob/9778be11d9214a0e1e93cfe74a34a41699c34940/src/components/commons/Buttons/NormalButton.jsx#L23-L28
이 부분에 삼항 연산자가 깊네요 이럴경우 util 함수 하나로 분리해서 좀 더 가독성을 챙겨보셔도 좋습니다.

나머지 부분은 전반적으로 깔끔하게 작성해주셨고 UI 컴포넌트도 많이 분리하려는 시도를 해주셔서 좋았습니다!
희철님 고생 많으셨습니다!!

**Comment by heechul94** [comment]
피드백 감사합니다!!
